stages:
  - checks
  - build
  - test

linters:
  image: golangci/golangci-lint:latest
  stage: checks
  script:
    - make lint

build:
  image: golang:1.14.0
  stage: build
  script:
    - echo "Try build project"
    - make build

test:
  image: golang:1.14.0
  stage: test
  script:
    - make test